[functions]
  external_node_modules = ["taffy"]
[functions."one"]
  included_files = ["api/_files/data/one/*.json","api/_files/nav/one/keywords.json"]
[functions."one-navfirst"]
  included_files = ["api/_files/key/one/0-keywords.json"]
[functions."one-navsecond"]
  included_files = ["api/_files/key/one/1-keywords.json"]


[functions."two"]
  included_files = ["api/_files/data/two/*.json","api/_files/nav/two/keywords.json"]
[functions."two-navfirst"]
  included_files = ["api/_files/key/two/0-keywords.json"]
[functions."two-navsecond"]
  included_files = ["api/_files/key/two/1-keywords.json"]


[functions."three"]
  included_files = ["api/_files/data/three/*.json","api/_files/nav/three/keywords.json"]
[functions."three-navfirst"]
  included_files = ["api/_files/key/three/0-keywords.json"]
[functions."three-navsecond"]
  included_files = ["api/_files/key/three/1-keywords.json"]


[functions."four"]
  included_files = ["api/_files/data/four/*.json","api/_files/nav/four/keywords.json"]
[functions."four-navfirst"]
  included_files = ["api/_files/key/four/0-keywords.json"]
[functions."four-navsecond"]
  included_files = ["api/_files/key/four/1-keywords.json"]



[functions."diger"]
  included_files = ["api/_files/data/diger/*.json","api/_files/nav/diger/keywords.json"]
[functions."diger-navfirst"]
  included_files = ["api/_files/key/diger/0-keywords.json"]
[functions."diger-navsecond"]
  included_files = ["api/_files/key/diger/1-keywords.json"]