[functions]
  external_node_modules = ["taffy"]
[functions."one"]
  included_files = ["api/_files/data/one/*.json","api/_files/nav/keywords.json"]
[functions."one-navfirst"]
  included_files = ["api/_files/key/one/0-keywords.json"]
[functions."one-navsecond"]
  included_files = ["api/_files/key/one/1-keywords.json"]


[functions."two"]
  included_files = ["api/_files/data/two/*.json","api/_files/nav/keywords.json"]
[functions."two-navfirst"]
  included_files = ["api/_files/key/two/0-keywords.json"]
[functions."two-navsecond"]
  included_files = ["api/_files/key/two/1-keywords.json"]


[functions."three"]
  included_files = ["api/_files/data/three/*.json","api/_files/nav/keywords.json"]
[functions."three-navfirst"]
  included_files = ["api/_files/key/three/0-keywords.json"]
[functions."three-navsecond"]
  included_files = ["api/_files/key/three/1-keywords.json"]


[functions."four"]
  included_files = ["api/_files/data/four/*.json","api/_files/nav/keywords.json"]
[functions."four-navfirst"]
  included_files = ["api/_files/key/four/0-keywords.json"]
[functions."four-navsecond"]
  included_files = ["api/_files/key/four/1-keywords.json"]



[functions."diger"]
  included_files = ["api/_files/data/diger/*.json","api/_files/nav/keywords.json"]
[functions."diger-navfirst"]
  included_files = ["api/_files/key/diger/0-keywords.json"]
[functions."diger-navsecond"]
  included_files = ["api/_files/key/diger/1-keywords.json"]


[functions."five"]
  included_files = ["api/_files/data/five/*.json","api/_files/nav/keywords.json"]
[functions."five-navfirst"]
  included_files = ["api/_files/key/five/0-keywords.json"]
[functions."five-navsecond"]
  included_files = ["api/_files/key/five/1-keywords.json"]


[functions."six"]
  included_files = ["api/_files/data/six/*.json","api/_files/nav/keywords.json"]
[functions."six-navfirst"]
  included_files = ["api/_files/key/six/0-keywords.json"]
[functions."six-navsecond"]
  included_files = ["api/_files/key/six/1-keywords.json"]


[functions."seven"]
  included_files = ["api/_files/data/seven/*.json","api/_files/nav/keywords.json"]
[functions."seven-navfirst"]
  included_files = ["api/_files/key/seven/0-keywords.json"]
[functions."seven-navsecond"]
  included_files = ["api/_files/key/seven/1-keywords.json"]


[functions."eight"]
  included_files = ["api/_files/data/eight/*.json","api/_files/nav/keywords.json"]
[functions."eight-navfirst"]
  included_files = ["api/_files/key/eight/0-keywords.json"]
[functions."eight-navsecond"]
  included_files = ["api/_files/key/eight/1-keywords.json"]


[functions."nine"]
  included_files = ["api/_files/data/nine/*.json","api/_files/nav/keywords.json"]
[functions."nine-navfirst"]
  included_files = ["api/_files/key/nine/0-keywords.json"]
[functions."nine-navsecond"]
  included_files = ["api/_files/key/nine/1-keywords.json"]


[functions."ten"]
  included_files = ["api/_files/data/ten/*.json","api/_files/nav/keywords.json"]
[functions."ten-navfirst"]
  included_files = ["api/_files/key/ten/0-keywords.json"]
[functions."ten-navsecond"]
  included_files = ["api/_files/key/ten/1-keywords.json"]

[functions."eleven"]
  included_files = ["api/_files/data/eleven/*.json","api/_files/nav/keywords.json"]
[functions."eleven-navfirst"]
  included_files = ["api/_files/key/eleven/0-keywords.json"]
[functions."eleven-navsecond"]
  included_files = ["api/_files/key/eleven/1-keywords.json"]


[functions."twelve"]
  included_files = ["api/_files/data/twelve/*.json","api/_files/nav/keywords.json"]
[functions."twelve-navfirst"]
  included_files = ["api/_files/key/twelve/0-keywords.json"]
[functions."twelve-navsecond"]
  included_files = ["api/_files/key/twelve/1-keywords.json"]




[functions."thirteen"]
  included_files = ["api/_files/data/thirteen/*.json","api/_files/nav/keywords.json"]
[functions."thirteen-navfirst"]
  included_files = ["api/_files/key/thirteen/0-keywords.json"]
[functions."thirteen-navsecond"]
  included_files = ["api/_files/key/thirteen/1-keywords.json"]

[functions."fourteen"]
  included_files = ["api/_files/data/fourteen/*.json","api/_files/nav/keywords.json"]
[functions."fourteen-navfirst"]
  included_files = ["api/_files/key/fourteen/0-keywords.json"]
[functions."fourteen-navsecond"]
  included_files = ["api/_files/key/fourteen/1-keywords.json"]



[functions."fifteen"]
  included_files = ["api/_files/data/fifteen/*.json","api/_files/nav/keywords.json"]
[functions."fifteen-navfirst"]
  included_files = ["api/_files/key/fifteen/0-keywords.json"]
[functions."fifteen-navsecond"]
  included_files = ["api/_files/key/fifteen/1-keywords.json"]


[functions."sixteen"]
  included_files = ["api/_files/data/sixteen/*.json","api/_files/nav/keywords.json"]
[functions."sixteen-navfirst"]
  included_files = ["api/_files/key/sixteen/0-keywords.json"]
[functions."sixteen-navsecond"]
  included_files = ["api/_files/key/sixteen/1-keywords.json"]


[functions."seventeen"]
  included_files = ["api/_files/data/seventeen/*.json","api/_files/nav/keywords.json"]
[functions."seventeen-navfirst"]
  included_files = ["api/_files/key/seventeen/0-keywords.json"]
[functions."seventeen-navsecond"]
  included_files = ["api/_files/key/seventeen/1-keywords.json"]

[functions."eighteen"]
  included_files = ["api/_files/data/eighteen/*.json","api/_files/nav/keywords.json"]
[functions."eighteen-navfirst"]
  included_files = ["api/_files/key/eighteen/0-keywords.json"]
[functions."eighteen-navsecond"]
  included_files = ["api/_files/key/eighteen/1-keywords.json"]


[functions."nineteen"]
  included_files = ["api/_files/data/nineteen/*.json","api/_files/nav/keywords.json"]
[functions."nineteen-navfirst"]
  included_files = ["api/_files/key/nineteen/0-keywords.json"]
[functions."nineteen-navsecond"]
  included_files = ["api/_files/key/nineteen/1-keywords.json"]


[functions."twenty"]
  included_files = ["api/_files/data/twenty/*.json","api/_files/nav/keywords.json"]
[functions."twenty-navfirst"]
  included_files = ["api/_files/key/twenty/0-keywords.json"]
[functions."twenty-navsecond"]
  included_files = ["api/_files/key/twenty/1-keywords.json"]


[functions."twenty-one"]
  included_files = ["api/_files/data/twenty-one/*.json","api/_files/nav/keywords.json"]
[functions."twenty-one-navfirst"]
  included_files = ["api/_files/key/twenty-one/0-keywords.json"]
[functions."twenty-one-navsecond"]
  included_files = ["api/_files/key/twenty-one/1-keywords.json"]


[functions."twenty-two"]
  included_files = ["api/_files/data/twenty-two/*.json","api/_files/nav/keywords.json"]
[functions."twenty-two-navfirst"]
  included_files = ["api/_files/key/twenty-two/0-keywords.json"]
[functions."twenty-two-navsecond"]
  included_files = ["api/_files/key/twenty-two/1-keywords.json"]


[functions."twenty-three"]
  included_files = ["api/_files/data/twenty-three/*.json","api/_files/nav/keywords.json"]
[functions."twenty-three-navfirst"]
  included_files = ["api/_files/key/twenty-three/0-keywords.json"]
[functions."twenty-three-navsecond"]
  included_files = ["api/_files/key/twenty-three/1-keywords.json"]


[functions."twenty-four"]
  included_files = ["api/_files/data/twenty-four/*.json","api/_files/nav/keywords.json"]
[functions."twenty-four-navfirst"]
  included_files = ["api/_files/key/twenty-four/0-keywords.json"]
[functions."twenty-four-navsecond"]
  included_files = ["api/_files/key/twenty-four/1-keywords.json"]


[functions."twenty-five"]
  included_files = ["api/_files/data/twenty-five/*.json","api/_files/nav/keywords.json"]
[functions."twenty-five-navfirst"]
  included_files = ["api/_files/key/twenty-five/0-keywords.json"]
[functions."twenty-five-navsecond"]
  included_files = ["api/_files/key/twenty-five/1-keywords.json"]


[functions."twenty-six"]
  included_files = ["api/_files/data/twenty-six/*.json","api/_files/nav/keywords.json"]
[functions."twenty-six-navfirst"]
  included_files = ["api/_files/key/twenty-six/0-keywords.json"]
[functions."twenty-six-navsecond"]
  included_files = ["api/_files/key/twenty-six/1-keywords.json"]


[functions."twenty-seven"]
  included_files = ["api/_files/data/twenty-seven/*.json","api/_files/nav/keywords.json"]
[functions."twenty-seven-navfirst"]
  included_files = ["api/_files/key/twenty-seven/0-keywords.json"]
[functions."twenty-seven-navsecond"]
  included_files = ["api/_files/key/twenty-seven/1-keywords.json"]


[functions."twenty-eight"]
  included_files = ["api/_files/data/twenty-eight/*.json","api/_files/nav/keywords.json"]
[functions."twenty-eight-navfirst"]
  included_files = ["api/_files/key/twenty-eight/0-keywords.json"]
[functions."twenty-eight-navsecond"]
  included_files = ["api/_files/key/twenty-eight/1-keywords.json"]


[functions."twenty-nine"]
  included_files = ["api/_files/data/twenty-nine/*.json","api/_files/nav/keywords.json"]
[functions."twenty-nine-navfirst"]
  included_files = ["api/_files/key/twenty-nine/0-keywords.json"]
[functions."twenty-nine-navsecond"]
  included_files = ["api/_files/key/twenty-nine/1-keywords.json"]


[functions."thirty"]
  included_files = ["api/_files/data/thirty/*.json","api/_files/nav/keywords.json"]
[functions."thirty-navfirst"]
  included_files = ["api/_files/key/thirty/0-keywords.json"]
[functions."thirty-navsecond"]
  included_files = ["api/_files/key/thirty/1-keywords.json"]
