[functions]
  external_node_modules = ["taffy"]
[functions."elbise"]
  included_files = ["api/_files/elbise/data/*.json","api/_files/elbise/nav/keywords.json"]
[functions."elbise-navfirst"]
  included_files = ["api/_files/elbise/nav/0-keywords.json"]
[functions."elbise-navsecond"]
  included_files = ["api/_files/elbise/nav/1-keywords.json"]
[functions."pantolon"]
  included_files = ["api/_files/pantolon/data/*.json","api/_files/pantolon/nav/keywords.json"]
[functions."pantolon-navfirst"]
  included_files = ["api/_files/pantolon/nav/0-keywords.json"]
[functions."pantolon-navsecond"]
  included_files = ["api/_files/pantolon/nav/1-keywords.json"]