[functions]
  external_node_modules = ["taffy"]
[functions."elbise"]
  included_files = ["api/_files/data/elbise/*.json","api/_files/nav/elbise/keywords.json"]
[functions."elbise-navfirst"]
  included_files = ["api/_files/key/elbise/0-keywords.json"]
[functions."elbise-navsecond"]
  included_files = ["api/_files/key/elbise/1-keywords.json"]

[functions."pantolon"]
  included_files = ["api/_files/data/pantolon/*.json","api/_files/nav/pantolon/keywords.json"]
[functions."pantolon-navfirst"]
  included_files = ["api/_files/key/pantolon/0-keywords.json"]
[functions."pantolon-navsecond"]
  included_files = ["api/_files/key/pantolon/1-keywords.json"]


[functions."etek"]
  included_files = ["api/_files/data/etek/*.json","api/_files/nav/etek/keywords.json"]
[functions."etek-navfirst"]
  included_files = ["api/_files/key/etek/0-keywords.json"]
[functions."etek-navsecond"]
  included_files = ["api/_files/key/etek/1-keywords.json"]



[functions."sweatshirt"]
  included_files = ["api/_files/data/sweatshirt/*.json","api/_files/nav/sweatshirt/keywords.json"]
[functions."sweatshirt-navfirst"]
  included_files = ["api/_files/key/sweatshirt/0-keywords.json"]
[functions."sweatshirt-navsecond"]
  included_files = ["api/_files/key/sweatshirt/1-keywords.json"]

[functions."gomlek"]
  included_files = ["api/_files/data/gomlek/*.json","api/_files/nav/gomlek/keywords.json"]
[functions."gomlek-navfirst"]
  included_files = ["api/_files/key/gomlek/0-keywords.json"]
[functions."gomlek-navsecond"]
  included_files = ["api/_files/key/gomlek/1-keywords.json"]


[functions."bluz"]
  included_files = ["api/_files/data/bluz/*.json","api/_files/nav/bluz/keywords.json"]
[functions."bluz-navfirst"]
  included_files = ["api/_files/key/bluz/0-keywords.json"]
[functions."bluz-navsecond"]
  included_files = ["api/_files/key/bluz/1-keywords.json"]


[functions."sort"]
  included_files = ["api/_files/data/şort/*.json","api/_files/nav/şort/keywords.json"]
[functions."sort-navfirst"]
  included_files = ["api/_files/key/şort/0-keywords.json"]
[functions."sort-navsecond"]
  included_files = ["api/_files/key/şort/1-keywords.json"]


[functions."tunik"]
  included_files = ["api/_files/data/tunik/*.json","api/_files/nav/tunik/keywords.json"]
[functions."tunik-navfirst"]
  included_files = ["api/_files/key/tunik/0-keywords.json"]
[functions."tunik-navsecond"]
  included_files = ["api/_files/key/tunik/1-keywords.json"]

[functions."tayt"]
  included_files = ["api/_files/data/tayt/*.json","api/_files/nav/tayt/keywords.json"]
[functions."tayt-navfirst"]
  included_files = ["api/_files/key/tayt/0-keywords.json"]
[functions."tayt-navsecond"]
  included_files = ["api/_files/key/tayt/1-keywords.json"]


[functions."atlet"]
  included_files = ["api/_files/data/atlet/*.json","api/_files/nav/atlet/keywords.json"]
[functions."atlet-navfirst"]
  included_files = ["api/_files/key/atlet/0-keywords.json"]
[functions."atlet-navsecond"]
  included_files = ["api/_files/key/atlet/1-keywords.json"]

[functions."kazak"]
  included_files = ["api/_files/data/kazak/*.json","api/_files/nav/kazak/keywords.json"]
[functions."kazak-navfirst"]
  included_files = ["api/_files/key/kazak/0-keywords.json"]
[functions."kazak-navsecond"]
  included_files = ["api/_files/key/kazak/1-keywords.json"]

[functions."dis_giyim"]
  included_files = ["api/_files/data/dis_giyim/*.json","api/_files/nav/dis_giyim/keywords.json"]
[functions."dis_giyim-navfirst"]
  included_files = ["api/_files/key/dis_giyim/0-keywords.json"]
[functions."dis_giyim-navsecond"]
  included_files = ["api/_files/key/dis_giyim/1-keywords.json"]