[functions]
  external_node_modules = ["taffy"]
[functions."elbise"]
  included_files = ["api/_files/data/elbise/*.json","api/_files/nav/elbise/keywords.json"]
[functions."elbise-navfirst"]
  included_files = ["api/_files/key/elbise/0-keywords.json"]
[functions."elbise-navsecond"]
  included_files = ["api/_files/key/elbise/1-keywords.json"]

[functions."pantolon"]
  included_files = ["api/_files/data/pantolon/*.json","api/_files/nav/pantolon/keywords.json"]
[functions."pantolon-navfirst"]
  included_files = ["api/_files/key/pantolon/0-keywords.json"]
[functions."pantolon-navsecond"]
  included_files = ["api/_files/key/pantolon/1-keywords.json"]

[functions."tulum"]
  included_files = ["api/_files/data/tulum/*.json","api/_files/nav/tulum/keywords.json"]
[functions."tulum-navfirst"]
  included_files = ["api/_files/key/tulum/0-keywords.json"]
[functions."tulum-navsecond"]
  included_files = ["api/_files/key/tulum/1-keywords.json"]

[functions."etek"]
  included_files = ["api/_files/data/etek/*.json","api/_files/nav/etek/keywords.json"]
[functions."etek-navfirst"]
  included_files = ["api/_files/key/etek/0-keywords.json"]
[functions."etek-navsecond"]
  included_files = ["api/_files/key/etek/1-keywords.json"]

[functions."tisort"]
  included_files = ["api/_files/data/tişört/*.json","api/_files/nav/tişört/keywords.json"]
[functions."tisort-navfirst"]
  included_files = ["api/_files/key/tişört/0-keywords.json"]
[functions."tisort-navsecond"]
  included_files = ["api/_files/key/tişört/1-keywords.json"]

[functions."hirka"]
  included_files = ["api/_files/data/hırka/*.json","api/_files/nav/hırka/keywords.json"]
[functions."hirka-navfirst"]
  included_files = ["api/_files/key/hırka/0-keywords.json"]
[functions."hirka-navsecond"]
  included_files = ["api/_files/key/hırka/1-keywords.json"]

[functions."sweatshirt"]
  included_files = ["api/_files/data/sweatshirt/*.json","api/_files/nav/sweatshirt/keywords.json"]
[functions."sweatshirt-navfirst"]
  included_files = ["api/_files/key/sweatshirt/0-keywords.json"]
[functions."sweatshirt-navsecond"]
  included_files = ["api/_files/key/sweatshirt/1-keywords.json"]

[functions."gomlek"]
  included_files = ["api/_files/data/gömlek/*.json","api/_files/nav/gömlek/keywords.json"]
[functions."gomlek-navfirst"]
  included_files = ["api/_files/key/gömlek/0-keywords.json"]
[functions."gomlek-navsecond"]
  included_files = ["api/_files/key/gömlek/1-keywords.json"]


[functions."bluz"]
  included_files = ["api/_files/data/bluz/*.json","api/_files/nav/bluz/keywords.json"]
[functions."bluz-navfirst"]
  included_files = ["api/_files/key/bluz/0-keywords.json"]
[functions."bluz-navsecond"]
  included_files = ["api/_files/key/bluz/1-keywords.json"]


[functions."sort"]
  included_files = ["api/_files/data/şort/*.json","api/_files/nav/şort/keywords.json"]
[functions."sort-navfirst"]
  included_files = ["api/_files/key/şort/0-keywords.json"]
[functions."sort-navsecond"]
  included_files = ["api/_files/key/şort/1-keywords.json"]

[functions."ceket"]
  included_files = ["api/_files/data/ceket/*.json","api/_files/nav/ceket/keywords.json"]
[functions."ceket-navfirst"]
  included_files = ["api/_files/key/ceket/0-keywords.json"]
[functions."ceket-navsecond"]
  included_files = ["api/_files/key/ceket/1-keywords.json"]

[functions."tunik"]
  included_files = ["api/_files/data/tunik/*.json","api/_files/nav/tunik/keywords.json"]
[functions."tunik-navfirst"]
  included_files = ["api/_files/key/tunik/0-keywords.json"]
[functions."tunik-navsecond"]
  included_files = ["api/_files/key/tunik/1-keywords.json"]

[functions."tayt"]
  included_files = ["api/_files/data/tayt/*.json","api/_files/nav/tayt/keywords.json"]
[functions."tayt-navfirst"]
  included_files = ["api/_files/key/tayt/0-keywords.json"]
[functions."tayt-navsecond"]
  included_files = ["api/_files/key/tayt/1-keywords.json"]

[functions."trenckot"]
  included_files = ["api/_files/data/trençkot/*.json","api/_files/nav/trençkot/keywords.json"]
[functions."trenckot-navfirst"]
  included_files = ["api/_files/key/trençkot/0-keywords.json"]
[functions."trenckot-navsecond"]
  included_files = ["api/_files/key/trençkot/1-keywords.json"]

[functions."mont"]
  included_files = ["api/_files/data/mont/*.json","api/_files/nav/mont/keywords.json"]
[functions."mont-navfirst"]
  included_files = ["api/_files/key/mont/0-keywords.json"]
[functions."mont-navsecond"]
  included_files = ["api/_files/key/mont/1-keywords.json"]

[functions."kaban"]
  included_files = ["api/_files/data/kaban/*.json","api/_files/nav/kaban/keywords.json"]
[functions."kaban-navfirst"]
  included_files = ["api/_files/key/kaban/0-keywords.json"]
[functions."kaban-navsecond"]
  included_files = ["api/_files/key/kaban/1-keywords.json"]

[functions."yagmurluk"]
  included_files = ["api/_files/data/yağmurluk/*.json","api/_files/nav/yağmurluk/keywords.json"]
[functions."yagmurluk-navfirst"]
  included_files = ["api/_files/key/yağmurluk/0-keywords.json"]
[functions."yagmurluk-navsecond"]
  included_files = ["api/_files/key/yağmurluk/1-keywords.json"]

[functions."atlet"]
  included_files = ["api/_files/data/atlet/*.json","api/_files/nav/atlet/keywords.json"]
[functions."atlet-navfirst"]
  included_files = ["api/_files/key/atlet/0-keywords.json"]
[functions."atlet-navsecond"]
  included_files = ["api/_files/key/atlet/1-keywords.json"]

[functions."abiye"]
  included_files = ["api/_files/data/abiye/*.json","api/_files/nav/abiye/keywords.json"]
[functions."abiye-navfirst"]
  included_files = ["api/_files/key/abiye/0-keywords.json"]
[functions."abiye-navsecond"]
  included_files = ["api/_files/key/abiye/1-keywords.json"]