[functions]
  external_node_modules = ["taffy"]
[functions."elbise"]
  included_files = ["api/_files/data/elbise/*.json","api/_files/nav/elbise/keywords.json"]
[functions."elbise-navfirst"]
  included_files = ["api/_files/key/elbise/0-keywords.json"]
[functions."elbise-navsecond"]
  included_files = ["api/_files/key/elbise/1-keywords.json"]

[functions."pantolon"]
  included_files = ["api/_files/data/pantolon/*.json","api/_files/nav/pantolon/keywords.json"]
[functions."pantolon-navfirst"]
  included_files = ["api/_files/key/pantolon/0-keywords.json"]
[functions."pantolon-navsecond"]
  included_files = ["api/_files/key/pantolon/1-keywords.json"]

[functions."tulum"]
  included_files = ["api/_files/data/tulum/*.json","api/_files/nav/tulum/keywords.json"]
[functions."tulum-navfirst"]
  included_files = ["api/_files/key/tulum/0-keywords.json"]
[functions."tulum-navsecond"]
  included_files = ["api/_files/key/tulum/1-keywords.json"]

[functions."etek"]
  included_files = ["api/_files/data/etek/*.json","api/_files/nav/etek/keywords.json"]
[functions."etek-navfirst"]
  included_files = ["api/_files/key/etek/0-keywords.json"]
[functions."etek-navsecond"]
  included_files = ["api/_files/key/etek/1-keywords.json"]

[functions."tisort"]
  included_files = ["api/_files/data/tişört/*.json","api/_files/nav/tişört/keywords.json"]
[functions."tisort-navfirst"]
  included_files = ["api/_files/key/tişört/0-keywords.json"]
[functions."tisort-navsecond"]
  included_files = ["api/_files/key/tişört/1-keywords.json"]

[functions."hirka"]
  included_files = ["api/_files/data/hırka/*.json","api/_files/nav/hırka/keywords.json"]
[functions."hirka-navfirst"]
  included_files = ["api/_files/key/hırka/0-keywords.json"]
[functions."hirka-navsecond"]
  included_files = ["api/_files/key/hırka/1-keywords.json"]

[functions."sweatshirt"]
  included_files = ["api/_files/data/sweatshirt/*.json","api/_files/nav/sweatshirt/keywords.json"]
[functions."sweatshirt-navfirst"]
  included_files = ["api/_files/key/sweatshirt/0-keywords.json"]
[functions."sweatshirt-navsecond"]
  included_files = ["api/_files/key/sweatshirt/1-keywords.json"]

[functions."gomlek"]
  included_files = ["api/_files/data/gömlek/*.json","api/_files/nav/gömlek/keywords.json"]
[functions."gomlek-navfirst"]
  included_files = ["api/_files/key/gömlek/0-keywords.json"]
[functions."gomlek-navsecond"]
  included_files = ["api/_files/key/gömlek/1-keywords.json"]