[functions]
  external_node_modules = ["taffy"]
[functions."elbise"]
  included_files = ["api/_files/elbise/data/*.json","api/_files/elbise/nav/keywords.json"]
[functions."elbise"."navfirst"]
  included_files = ["api/_files/elbise/nav/0-keywords.json"]
[functions."pantolon"]
  included_files = ["api/_files/pantolon/data/*.json","api/_files/pantolon/nav/keywords.json"]