[functions]
  external_node_modules = ["taffy"]
[functions."elbise"]
  included_files = ["api/_files/data/gömlek/*.json","api/_files/nav/gömlek/keywords.json"]
[functions."elbise-navfirst"]
  included_files = ["api/_files/key/gömlek/0-keywords.json"]
[functions."elbise-navsecond"]
  included_files = ["api/_files/key/gömlek/1-keywords.json"]
[functions."pantolon"]
  included_files = ["api/_files/data/tişört/*.json","api/_files/nav/tişört/keywords.json"]
[functions."pantolon-navfirst"]
  included_files = ["api/_files/key/tişört/0-keywords.json"]
[functions."pantolon-navsecond"]
  included_files = ["api/_files/key/tişört/1-keywords.json"]


