name: callertest
on:
   workflow_dispatch:

env:
  VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
  NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
jobs:
  test_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: defacto
    secrets: inherit

  generate_nav_job:
    runs-on: ubuntu-latest
    needs: [test_job]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS...
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: 'npm install'
      - name: Install vercel cli
        run: 'npm i -g vercel'
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: data
          path: projects/dream/api/_files/elbise/data
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: projects
      - name: Decript data
        run: 'npm run decryptData'
      - name: gen nav
        id: genegateNavigation
        run: node utils/genegateNavigation.js
      - name: deploytonetlify
        env:
          NETLIFY_SITE_ID:  "41dc1cc1-4401-4d93-9139-207230925314"
        run: 'npm run deploy'